### PR TITLE
remove sensitive infos from code

### PR DESCRIPTION
**Pull request by ltclm**
this pr will remove the following sensitive information from the code:
DB Superuser
SPHINX Deploy target IP's
the info can be read from env variables or sourced from deploy.cfg

### CODE REVIEW

**Comment by ltclm** [comment]
@danduk82 can we merge this one?

**Comment by danduk82** [comment]
@ltclm This commit seems legit to me. Do you already use it in this present form when deploying?
I.e. are the needed informations already in ENV variables or .cfg files?

If yes, you can merge it.

**Comment by ltclm** [comment]
Hello, no this code is not yet used.
But when we merge this one, i will create a deploy.cfg file with this information before updating the code on our pg master instance.
Without this file or env variables the script is not running.

**Comment by danduk82** [comment]
Ok. Can you merge it when the deploy.cfg file is created and you have tested it first locally?

**Pull request merged**
